### ISSUE TITLE
[SDL1/2]: Freeze/Crash when closing a windowed SDL app (OpenGL)

### ISSUE THREAD

**Issue by raziel-** [AmigaPorts/SDL_old#30]
Both ScummVM and ResidualVM are freezing when i close the app in wndowed mode.

Not always, but i can make it crash in two to five tries.

More information here:
http://www.amigans.net/modules/xforum/viewtopic.php?post_id=110899#forumpost110899

**Comment by raziel-** [comment]
Is there any more information needed?
I can provide if it isn't something code-wise or even a PR :-)

**Comment by capehill** [comment]
Yes, I'm confused because if I remember correctly, you told me earlier that the problem was gone when serial debug prints were disabled in the SDL2 binary. If it happens without debug prints too, then problem is not directly related to them but could be some nasty race condition in the system related to resource cleanup, and debug prints only changed the probability for the freeze.

I wonder could OS4 debug kernel get more data?

**Comment by raziel-** [comment]
I guess that was a misunderstanding on my side, sorry about that.

It still happens, reproducable every time i try it.

Tell me what to do, i'm right now not on kernel.debug, but can easily turn it on for testing

**Comment by raziel-** [comment]
For whatever reason...it doesnß t crash or freeze anymore.

I just did a thoroughly test with different renderers/graphic modes, and with differing games, from within the games and from the launcher.
For the life of me i can't get it to crash.

So, i'm closing this issue for now to prevent further work done on it and will reopen *if* this ever surfaces again.

Sorry for the noise

**Comment by raziel-** [comment]
Reopening this as it's back and got even worse.
Not sure if a change in the ScummVM code made it reappear or the fact that i'm using and testing the OpenGL renderer (from ScummVM's options) only for some time now.

It got worse due to freezing not only when closing the window, but by simply reactivating the window after activating WB (but, of course, not reproducable).
It's now freezing even when i e.g. press ESC to make an intro skip, or by simply clicking through the options dialogs... :-(
The same works fine in fullscreen.

There is nothing on serial though.
I could use a freshup on doing debug logs, please

**Comment by capehill** [comment]
As a first step, please link with debug version of SDL2 library.

We could try to add some kernel debug features next.

Do you know whether ScummVM is actively tested with Valgrind or clang sanitizer tools?

Does it happen on SDL1?

**Comment by raziel-** [comment]
I'll try and get some logs saved.
Would the SDL2_debug4 from your download site be sufficient?

Yes, i know that both (valgrind and clang sanitizer) are sporadically used to rule out newly introduced memory leaks (judging by the scummvm-devel mailinglist), but i'm pretty sure they use it (unseen by the "puiblic eye" or rather mere users like me) on a much more frequent basis.

I need to build a SDL1 version first :-)
Too much juggling with different versions, i really need to rename my trees...

**Comment by raziel-** [comment]
One more thing...do i need to install the whole SDL_debug (renaming the installed one in the process) or would copying libSDL2.a be enough?

**Comment by capehill** [comment]
You should be able to use the _debug.a lib from the latest public release ( http://os4depot.net/index.php?function=showcontent&file=library/misc/sdl2.lha ). Modify your makefile to link with SDL2_debug instead of just SDL2. No renaming should be necessary. You should be able too see on serial log that correct library is linked.

Do you have a possibility to test issue with a clean OS4 installation, to rule out possible external sources for the problem?

**Comment by raziel-** [comment]
I don't have a clean installation per se, but i can alwyays boot with the installation CD and add assigns where needed?

**Comment by raziel-** [comment]
[Serial_SDL2_OpenGL.txt](https://github.com/AmigaPorts/SDL/files/2626318/Serial_SDL2_OpenGL.txt)
[Serial_SDL2_OpenGL_2.txt](https://github.com/AmigaPorts/SDL/files/2626319/Serial_SDL2_OpenGL_2.txt)

First one is starting in fullscreen mode, switching to window mode (Alt+Enter) and closing with the window gadget and freeze.
Second one is starting in window mode, closing with the window gadget (everything went well), starting again in window mode, closing again with the window gadget and freeze

**Comment by raziel-** [comment]
Some more tests reveal that it ONLY happens with the OpenGL renderer in place, so it might very well be a problem in MiniGL(?)

**Comment by capehill** [comment]
I tried to reproduce the issue more than 10 times using one of your builds, no luck on my env.

I know it's a bit desperate but could you setup debug kernel, I can see some instructions here: https://wiki.amigaos.net/wiki/Debug_Kernel

Set debug level to 5, and enable munge. Let's see what happens.

Can you perhaps reproduce the issue with some MiniGL demos, such as Gears? http://os4depot.net/index.php?function=showcontent&file=driver/graphics/minigl.lha

**Comment by raziel-** [comment]
Done.
But i'm afraid i can't really add anything to the cause.

It took 9 tries this time to get it to freeze, but frozen it was.

[Serial_Crashlog.txt](https://github.com/AmigaPorts/SDL/files/2682866/Serial_Crashlog.txt)

**Comment by raziel-** [comment]
No problems with "gears", at least not the 30 times in a row i tried

**Comment by capehill** [comment]
Improved logging with PR #46 and also disabled the window hiding upon close, even though it was earlier concluded not to be an issue.

**Comment by raziel-** [comment]
Nice, is there a debug build i could test?

**Comment by capehill** [comment]
Not right now, but it should be simple to build your own library. Just clone, configure (see readme) and make.

**Comment by raziel-** [comment]
Thanks for the hint, no time right now unfortunately

**Comment by raziel-** [comment]
Another idea sprang to mind.

Since i had "similar" problems with *debug* builds on a completely different source, would it be possible to provide a test build with all debug turned off?
Just to rule out some sneaky "debug-only" issue...

**Comment by capehill** [comment]
2.0.8 and 2.0.9 have 2 library versions, with or without debug. Actually 4 if you count also static and dynamic.

**Comment by capehill** [comment]
Any results for 2.0.9 RC1?

**Comment by raziel-** [comment]
Unfortunately still the same 100% freeze on closing the window while using OpenGL as renderer on both the debug and non-debug build

**Comment by capehill** [comment]
Serial logs?

**Comment by raziel-** [comment]
Yes, sorry, short on time and pretty much to do here beside the amiga, will add them next

**Comment by raziel-** [comment]
[Debug_Serial.txt](https://github.com/AmigaPorts/SDL/files/2872018/Debug_Serial.txt)

1) Start in windowed mode
2) Close, everything went fine
3) Immediatelay started again in windowed mode
4) Close, freeze

**Comment by raziel-** [comment]
With no_debug exe it takes 5-10 tries to make it freeze, but freeze it will :-(

**Comment by capehill** [comment]
Thanks for the log. The last print is before image disposal (is it now always there?) so it might indicate something wrong with iconification. I could still improve the debug prints to include pointer addresses and reorder the code: I can see AWeb first closes its window, and disposes gadget afterwards. AWeb also doesn't also explicitly RemoveGadget so I can try to remove that. It's strange.

Are you certain it's MiniGL-related issue only? As far as I can see, the context is deleted before the freeze so it's difficult to see connection.

Or maybe it's related to OS4_SetWindowGrabPrivate? Quite a puzzle.

**Comment by raziel-** [comment]
It's quite a struggle to test the freeze as it's sending my hardware into quite a deep crash afterwards.
Means, when i get that freeze, i have to manually switch off the hardware, becausea reset button press won't be sufficient. Even a shut off and on again won't do, i have to shut it down and let ti sit there at least a minute before retrying to start it up.
Not sure if it is related to something hardware (like the gfx card), but it feels like some of the mounted hardware gets sent into a quite deep crash aswell, just guessing here.

I'll try to catch some more logs and compare the output, will report back.

Yes, i'm 100% sure it's OpenGL/MiniGL, because if i set the renderer (inside ScummVM's options) to naything else than OpenGL the freeze is nowhere to be seen.

If it won't take away any more of your precious coding time i'd be glad to test an improved debug build, but no need to rush it, i'm off to work soon, so take your time.

Regarding your iconification remark, just fyi, i haven't added the new iconification code to ScummVM you added lately, if that makes any difference.

**Comment by raziel-** [comment]
I "seem" to be getting some sort of pattern here.

It's not always freezing at that line
[OS4_CloseWindow] Disposing gadget image

Sometimes it's freezing at the line before
[OS4_CloseWindow] Removing gadget and disposing it

But that happens only when i need a few tries to make it freeze.

So, when it freezes the very first time i run ScummVM, then it will freeze while still displaying this line
[OS4_CloseWindow] Disposing gadget image

But when it succesfully closes a first (and maybe more instances afterwards) ScummVM, then it will freeze already one line above at
[OS4_CloseWindow] Removing gadget and disposing it
without ever displaying line
[OS4_CloseWindow] Disposing gadget image

Not very helpful, i know

**Comment by capehill** [comment]
Ok, thanks. I will try to improvise something for the next RC.

By the way, you don't need to activate iconifying feature. It (extra gadget) should be there in window mode.

There is an option to build also a serial debug version of MiniGL.

**Comment by raziel-** [comment]
Ah, ok.
I never realized that the iconifying Gadget is already available.
Need zu try that when I get home...maybe it will crash aswell, so we can corner it finally.

Wrt debug minigl: I'd try anything to get this annoying crash fixed

**Comment by raziel-** [comment]
@capehill

Ok, so it seems there is something wrong with my (SDL2) window(s).

You stated that the extra iconify gadget should be there, nonetheless of having specific code (for iconifying) in place/in source...but it isn't for me.
The window looks like any normal WB directory window (left is the "close" gadget, and on the right far end is the "maximiize/minimize" gadget, followed by the "bring to front/back" gadget, but there is no "iconify" gadget to be seen.

Was it introduced in some specific version which i probably not have installed yet?
How can i (easily) check my SDL2 (SDK) version?
Because i now fear that i am doing tests with an obsolete version of SDL2...

**Comment by raziel-** [comment]
This is what i have in SDL_version.h

#define SDL_MAJOR_VERSION   2
#define SDL_MINOR_VERSION   0
#define SDL_PATCHLEVEL      9

**Comment by capehill** [comment]
Like this: https://wiki.libsdl.org/SDL_GetVersion

You should have 4 gadgets in title bar. Found this screen on AW.net thread: http://kas1e.mikendezign.com/aos4/sdl2_iconify_01.jpg

**Comment by raziel-** [comment]
I'll try GetVersion when I get home again.
Nope, no underscore gadget for me.
null

**Comment by capehill** [comment]
At least in Debug_serial.txt you sent earlier, contains "[OS4_CreateIconifyGadget] Called". If you don't get the gadget, check serial logs (use _debug variant of the library).

**Comment by raziel-** [comment]
Hmm, I'll check again once I'm home. Strange...
null

**Comment by raziel-** [comment]
@capehill 

Sorry for mixing up this issue report.
I can open a new one for the iconify problem if you want?

Anyway, i did a simple test and can reprocude the "vanishing iconify gadget" every time.

Steps to reproduce are simply by switching to full screen and back to window, or by starting in fullscreen mode and switching to window, then there won´t ever be an iconify gadget seen.
If i start the app in window mode the gadget is drawn and usable, but only this time.

So i guess there is a "redraw", "recall" problem when switching back to window mode.

I added a debug serial log where the app was started in window mode, the iconify gadget is drawn and usable. Then i switched to fullscreen and back to window mode. As you can see the iconify gadget is not called and will never be after that.
It seems the only call is done when the app is started in window mode.

I added a freeze script as well. This time when the app started to close it´s window while switching back to fullscreen mode.

There is something wrong with the SDL windows, it seems, unfortunately the crashlog does not not hold any new information, i fear.

[Debug_Serial.txt](https://github.com/AmigaPorts/SDL/files/2951250/Debug_Serial.txt)
[Serial_Crashlog.txt](https://github.com/AmigaPorts/SDL/files/2951251/Serial_Crashlog.txt)

**Comment by capehill** [comment]
Ok, I get the iconification issue now: it seems that you have reproduced #53 which is fixed on the master branch but not yet released. So 2.0.9 RC2 should correct it.

Regarding freeze, some debug logging improvements were done also.

**Comment by raziel-** [comment]
@capehill

I am finally able to build the SDL1 version of ScummVM again and tests show that the freeze also happens with SDL1. So it's a general problem of SDL (but in conjunction with using OpenGL).

Do you happen to have an SDL1 debug library too?
I could do some logging with SDL1, maybe it will show some new stuff happening.

The problem i'm facing right now is that i'm not sure which of the affected parts is really the culprit.
It could be SDL in general, or only the windows part, maybe even reduced to something breaking in the OpenGL implementation of SDL.
Then it could as well be some (maybe already fixed, but not yet released) bug in minigl (since this is used, as i understand it, once an app uses OpenGL features through SDL1/2(?))

There should be a minigl debug build as well, i think

**Comment by capehill** [comment]
@raziel- https://github.com/AmigaPorts/SDL/releases/tag/v1.2.15-rc1-amigaos4 you could try the debug libraries here. 

I will add MiniGL debug library on my TODO list. What is the full version of your minigl.library? Which GFX card you are using?

**Comment by raziel-** [comment]
@capehill 

Thank you for the debug builds.
This Problem is also visible with  SDL1.

First log is closing the window successfully the first time, but freezing the second time (closing and restarting the app without doing anthing else in between).
Last lines displayed on serial:
[os4video_DeleteCurrentDisplay] Removing gadget
[os4video_DeleteCurrentDisplay] Disposing image

Second log is right after reboot, closing the window right after opening (two times successful, third time freeze).
Last line displayed this time only
[os4video_DeleteCurrentDisplay] Removing gadget

I need to add something:
The first time the window´s contents were erased (Disposing image?), so the window froze with no contents aka black background inside the window borders.
The second time the window´s contents were still there when it froze (Disposing image never called?).
[Serial_SDL1_OpenGL.txt](https://github.com/AmigaPorts/SDL/files/2969961/Serial_SDL1_OpenGL.txt)
[Serial_SDL1_OpenGL_2.txt](https://github.com/AmigaPorts/SDL/files/2969962/Serial_SDL1_OpenGL_2.txt)

**Comment by raziel-** [comment]
SDL2.0.9RC2 - MiniGL2.23

Still happening, i´m afraid.
Also, nothing really new in the log (took me four tries to make it freeze)
[Serial_Crashlog.txt](https://github.com/AmigaPorts/SDL/files/2987810/Serial_Crashlog.txt)

**Comment by capehill** [comment]
After reading this http://www.amigans.net/modules/xforum/viewtopic.php?forum=3&topic_id=7991&order= ...could you please retest? It sounded similar issue.

**Comment by raziel-** [comment]
Will do, but i´m unsure about whether it´s really related, since i was able to fix it by switching the network card (problem never surfaced).

But i tried with some new builds the other day and it still freezes.

**Comment by raziel-** [comment]
I have partly good news.

ResidualVM SDL1 and SDL2 versions do not display this behaviour anymore.

ScummVM still to test

**Comment by raziel-** [comment]
ScummVM - SDL2 - behaviour is gone
ScummVM - SDL1 - not testable since it's still erroring due to the png stuff (hope to see a workaround in the app's tree soon)

**Comment by capehill** [comment]
You can modify config.mk to disable USE_PNG.

**Comment by raziel-** [comment]
Yes, i can use ScummVM's configure switch --disable-png aswell, but then it falls over at somne other image, writeBMP namely (used the switch, commented out USE_PNG and tried with USE_PNG=0, all the same)

    C++      backends/graphics/opengl/opengl-graphics.o
In file included from ./image/bmp.h:36,
                 from backends/graphics/opengl/opengl-graphics.cpp:50:
./image/image_decoder.h:37:11: error: 'namespace Image { }' redeclared as different kind of symbol
 namespace Image {
           ^~~~~
In file included from /SDK/include/include_h/intuition/intuitionbase.h:24,
                 from /SDK/include/include_h/proto/intuition.h:17,
                 from /sdk/local/newlib/include/SDL/SDL_syswm.h:55,
                 from ./backends/platform/sdl/sdl-sys.h:150,
                 from ./backends/graphics/opengl/opengl-sys.h:30,
                 from ./backends/graphics/opengl/opengl-graphics.h:26,
                 from backends/graphics/opengl/opengl-graphics.cpp:24:
/SDK/include/include_h/intuition/intuition.h:754:8: note: previous declaration 'struct Image'
 struct Image
        ^~~~~
In file included from backends/graphics/opengl/opengl-graphics.cpp:50:
./image/bmp.h:47:11: error: 'namespace Image { }' redeclared as different kind of symbol
 namespace Image {
           ^~~~~
In file included from /SDK/include/include_h/intuition/intuitionbase.h:24,
                 from /SDK/include/include_h/proto/intuition.h:17,
                 from /sdk/local/newlib/include/SDL/SDL_syswm.h:55,
                 from ./backends/platform/sdl/sdl-sys.h:150,
                 from ./backends/graphics/opengl/opengl-sys.h:30,
                 from ./backends/graphics/opengl/opengl-graphics.h:26,
                 from backends/graphics/opengl/opengl-graphics.cpp:24:
/SDK/include/include_h/intuition/intuition.h:754:8: note: previous declaration 'struct Image'
 struct Image
        ^~~~~
backends/graphics/opengl/opengl-graphics.cpp: In member function 'bool OpenGL::OpenGLGraphicsManager::saveScreenshot(const Common::String&) const':
backends/graphics/opengl/opengl-graphics.cpp:1227:16: error: 'writeBMP' is not a member of 'Image'
  return Image::writeBMP(out, data, true);
                ^~~~~~~~
gmake: *** [backends/graphics/opengl/opengl-graphics.o] Error 1

**Comment by capehill** [comment]
Hmm... it seems SDL-1.2 includes intuition.h (which includes the conflicting header with Image) to introduce struct Window* even though it's not really necessary. I think Window type could be forward-declared and make this particular problem go away.

Could you try to comment out line 

https://github.com/AmigaPorts/SDL/blob/SDL-1.2/include/SDL_syswm.h#L55

and add a new line with:

struct Window; // forward declare AmigaOS window

?

This conflict shouldn't happen with SDL2 though, at least not via SDL_syswm.h.

**Comment by raziel-** [comment]
I could, but i couldn't build a working SDL test version, so...waiting for a test release :-)

Sorry ;-)

**Comment by raziel-** [comment]
wrt the SDL2 version, yes, it doesn't happen, ScummVM builds happily with SDL2 and all bells and whistles in place.

It's ResidualVM which stumbles over the PNG issue (SDL1 and 2)

**Comment by capehill** [comment]
There is PR #85 now which should reduce possibility for conflict.

You don't actually need to build SDL to test it. Just modify locally SDL_syswm.h header.

**Comment by raziel-** [comment]
Ahh, ok, i see.

Done with the "struct Window;" inplace.
ScummVM builds again with sdl1, yay

And i did a quick 20 times test opening and closing scummvm SDL1 in window mode and closing it again immediately (built with no game engine, just the launcher) and it didn't freeze once.

Not sure what you did in those past revisions, but you nailed it :-)

Testing now to see if residualvm will work with png again

**Comment by raziel-** [comment]
Works aswell with your PR change.

ResidualVM refuses to build with PNG in place.
Might be a followup error to the PNG changes they did in  https://github.com/residualvm/residualvm/commit/119ff7f2f3ec9c8cf7204fa54f5376212e014e47
though reverting those doesn't help.

```
    C++      backends/graphics/surfacesdl/surfacesdl-graphics.o
backends/graphics/surfacesdl/surfacesdl-graphics.cpp: In member function 'virtual bool SurfaceSdlGraphicsManager::saveScreenshot(const Common::String&) const':
backends/graphics/surfacesdl/surfacesdl-graphics.cpp:512:13: error: 'width' was not declared in this scope
   data.init(width, height, screen->pitch, screen->pixels, format);
             ^~~~~
backends/graphics/surfacesdl/surfacesdl-graphics.cpp:512:20: error: 'height' was not declared in this scope
   data.init(width, height, screen->pitch, screen->pixels, format);
                    ^~~~~~
backends/graphics/surfacesdl/surfacesdl-graphics.cpp:512:20: note: suggested alternative: 'sig_t'
   data.init(width, height, screen->pitch, screen->pixels, format);
                    ^~~~~~
                    sig_t
gmake: *** [backends/graphics/surfacesdl/surfacesdl-graphics.o] Error 1
```

**Comment by raziel-** [comment]
Of course there may be some other change in the meantime, i haven't built the SDL1 version of residualvm for a looong time

**Comment by capehill** [comment]
> And i did a quick 20 times test opening and closing scummvm SDL1 in window mode and closing it again immediately (built with no game engine, just the launcher) and it didn't freeze once.
> 
> Not sure what you did in those past revisions, but you nailed it :-)

I don't think I have fixed anything, after all. This freeze that only you have managed to reproduce, remains unexplained to me, but I think your ethernet card (driver?) was related to it. You could go to older SDL revision to confirm that, of course.

Width and height variables are only declared for SDL2 compilation ( https://github.com/residualvm/residualvm/blob/master/backends/graphics/surfacesdl/surfacesdl-graphics.cpp#L480 ) but that line 512 isn't restricted to SDL2.

**Comment by raziel-** [comment]
It's wasn't the "old" ethernet card, nor did the new one fix it.
I tried with older versions and they still freeze immediately on closing. Very, very strange indeed.
I only hope that this doesn't come back anytime.

So, it could be a pickup error on the SDL1 side?

**Comment by capehill** [comment]
> It's wasn't the "old" ethernet card, nor did the new one fix it.
> I tried with older versions and they still freeze immediately on closing. Very, very strange indeed.
> I only hope that this doesn't come back anytime.

All modifications and logging changes regarding SDL cleanup were only done for SDL2. So if you say that freeze is also gone in SDL1, it's really strange.

> 
> So, it could be a pickup error on the SDL1 side?

Residual compilation? Yes.  Compiler doesn't know width and height then.

**Comment by raziel-** [comment]
To be 100% sure i just did a quick test with the latest SDL1 version of ScummVM (build yesterday)...no freezes.

wrt ResidualVM, how could i fix this?

**Comment by capehill** [comment]
"int width, height;" needs to be moved before line 480 ( https://github.com/residualvm/residualvm/blob/master/backends/graphics/surfacesdl/surfacesdl-graphics.cpp#L480 ), then it should work for both SDL versions.

**Comment by raziel-** [comment]
Thank you for always being helpful, you are gold :-)

Think we can close this?

**Comment by capehill** [comment]
Ok, I suppose reopen button is still there. Thanks.
