### ISSUE TITLE
White little dot where the hotspot of the mouse pointer is.

### ISSUE THREAD

**Issue by kas1e** [AmigaPorts/SDL_old#40]
As we discuss with Raziel lately, there is some issues in SDL2 apps, when postition of real amiga cursor can be seen in the SDL app as 1 pixel white dot. Usually it happens when you load system with something, or by any reassons sdl2 cursor going to be moving a little slower than usuall, and then, you can see that on the place where real amiga cursor was there is little dot showns. And , it start to be visibly together with SDL2 cursor. Like you move 2 cursors : one is SDL2 one, and another, cursor of the real amiga cursor, coming to the SDL2's like satellite :)

At moment we can't reproduce it 100% all the time easyly, i only can see that Raziel see it in ScummVM builded with SDL2/MiniGL, and i see it in Quake3 buillded with SDL2/GL4ES

Its like something not 100% erased when it should, or, draws instead while should't. Or like somewhere is 1,1 instead of 0,0 in the code.

Raziel says that problem is from the very first SDL2 releases , and he mention it somewhere when it was on other place (on sourceforge ?). 

At moment will try to find out some reproducable test case.

**Comment by raziel-** [comment]
Oh, but i have an "always" reproducable and "easy" way to (at least) show off the "double pointer" sprite problem :-)

@capehill

As always, fire up ScummVM
Choose "Options" (not really necessary, but i end up starting a game instead of switching modes)
Press LCTRL+ENTER (to switch to window mode)
--> All is well
Press LCTRL+ENTER again (to switch back to screen mode)
--> Double pointer sprite visible, where the original amiga pointer sprite is drawn above the ScummVM pointer sprite
Press LCTRL+ENTER again (to go once more back to window mode)
--> All is well again
etc.

Seems to be a problem of switching from window to screenmode.

I don't have a case for the "dot" problem, i rarely see it in scummvm nowadays - more so the doubled pointer, but maybe that will go away too once the doubled sprite has been dealt with.

I'm pretty sure that this is a genuine SDL2 bug (as it happens in any of the renderers, not only MiniGL and iirc it wasn't a problem in SDL1)

**Comment by capehill** [comment]
"Dot issue" may be caused by freeing the transparent image data too early. It's not very well documented but I get the feeling that data may need to be available to the system until pointer is freed. @kas1e could you try to comment out this FreeSurface and see what happens: https://github.com/AmigaPorts/SDL/blob/master/src/video/amigaos4/SDL_os4mouse.c#L175 

My theory is that after freeing, system may pull image data from some invalid memory and if you are lucky, you get white dot, if you are unlucky, kittens die. FYI: in test/helloworld.c, there is a trivial test case for hidden pointer - just needs activation.

@raziel-  "double pointer" issue is something different. Probably it has something to do with window activation. For example, if ScummVM disables system pointer, then ScummVM window gets deactivated, so system pointer pops up and you have 2 pointers magically.

Anyway, both issues can be tracked with this ticket for now.

**Comment by raziel-** [comment]
@capehill

Whoa, whoa, whoa, hold your horses
Why does it have to be kittens? :-)

On a more serious matter...
Could this (maybe/also) be the reason for the window (close/switch back to fullscreen) crash in #30?
You say that *if* it pulls some invalid data, then the system goes down...isn' tthat exactly whats happening?
Moreover so, that i cannot really track it with debug versions?
Invalid memory sounds good :-)

I'll at least keep my eye on this one, maybe you can hit two puppys with one stone (something like that) :-P

**Comment by kas1e** [comment]
@capehill 
Commenting out that FreeSurface, make dot disappear :) At least it tried hard to test if it is , and yes , can confirm that dot disappear then

**Comment by raziel-** [comment]
Regarding the "double pointer"
That could probably also cause the #30 freeze.

It sounds just too perfect.
On switching to window, nothing bad happens, never!

On closing/switching back to fullscreen, the second pointer sprite comes, so there's definitely something causing something wrong, which might be enough to pull my system down.

**Comment by kas1e** [comment]
My issue with white dot are fixed for sure latest commits, thanks !

**Comment by raziel-** [comment]
Is there a beta release, so i could test for the crash?

**Comment by kas1e** [comment]
I cross-compile it myself, but if you want it , there is: http://kas1e.mikendezign.com/aos4/sdl2/libSDL2_11083.zip

**Comment by raziel-** [comment]
Thank you, doesn't fix it for me though, but that was to be expected

**Comment by kas1e** [comment]
Well, i do not know if it related to the latest changes being made, or it there for a while since 2.0.8 release, but for now, just this simple test fail:

`#include <SDL2/SDL.h>`
`int main(int argc, char *argv[])`
`{`

`	if(SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER | SDL_INIT_EVENTS)!=0)`
`	{`
`		printf("Error initializing SDL2, aborting!\n");`
`		return -1;`
`	}`
`}`

I compile it, run , and it fail with words : Error initializing SDL2, aborting!

2.0.8 version works with that test case for sure. Maybe that happens when "PATH" defines was changed ?
